server:
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  ldap:
    urls: ${BASE_APP_LDAP_URI:ldap://localhost:8389}
    base: ${BASE_APP_LDAP_BASE:dc=sdf,dc=slac,dc=stanford,dc=edu}
  application:
    name: test-app
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB
      max-file-size: ${BASE_APP_MAX_POST_SIZE:100MB}
      max-request-size: ${BASE_APP_MAX_POST_SIZE:100MB}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
edu:
  stanford:
    slac:
      ad:
        eed:
          baselib:
            app-token-jwt-key: ${BASE_APP_APP_TOKEN_JWT}
            root-user-list: ${BASE_APP_ROOT_USERS}
            root-authentication-token-list-json: ${BASE_APP_ROOT_AUTHENTICATION_TOKEN_JSON}
            oauth-server-discover: ${BASE_APP_OIDC_CONFIGURATION_ENDPOINT:https://dex.slac.stanford.edu/.well-known/openid-configuration}
            user-header-name: ${BASE_APP_AUTH_HEADER:x-vouch-idp-accesstoken}
            autoload-user-authorizations: true
