name: MergeCheck
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: assemble
      - name: Test Project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: test
