name: MergeCheck
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Manage Version
        run: |
          echo "Modify build.gradle for with version number \"$GitVersion_LegacySemVerPadded\""
          sed -i "s#^.*version.*=.*#version = '$GitVersion_LegacySemVerPadded'#" build.gradle
          cat build.gradle
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21
      - name: Build project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: assemble
      - name: Test Project
        uses: gradle/gradle-build-action@v2
        env:
          CI: true
        with:
          arguments: test
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
